let b = True in let b = 10 in b;;
let b = True in let b = 10 in if b then b else 100;;
let f = fun x -> x in f;;
fun x -> x;;
let f = fun x -> x in let f = fun x -> fun y -> x in f 10;;
let f = fun x -> x + 11 in f;;
let f = fun x -> x in if f True then f 11 else 1;;
let rec f = fun x -> if 11 < x then 1 else  x * f (x + 1) in f 1;;
fun x -> x + 11;;
let f = fun x -> fun y -> x + y in f;;
let f = 10 in f;;
2 * 2;;
19;;
